import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { HeaderActions } from "@/components/header-actions";
import { TableSelector } from "@/components/table-selector";
import { AnalyticsButton } from "@/components/analytics-button";
import { ContextButton } from "@/components/context-button";
import { Providers } from "@/components/providers";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers>
            <Toaster />
            <SignedOut>
              <div className="flex min-h-screen items-center justify-center">
                <SignIn />
              </div>
              {children}
            </SignedOut>
            <SignedIn>
              <header className="flex h-16 shrink-0 items-center justify-between gap-2 border-b px-4">
                <div className="flex items-center gap-2">
                  <TableSelector />
                  <AnalyticsButton />
                  <ContextButton />
                </div>
                <div className="flex items-center gap-2">
                  <HeaderActions />
                  <UserButton />
                </div>
              </header>
              <div className="flex flex-1 flex-col gap-4 p-4">
                {children}
              </div>
            </SignedIn>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
